- name: install and start Nginx
  hosts: frontend
  become: yes ; with sudo user execute all the below tasks as it is mentioned in top level
  tasks:
  - name: Install Nginx package
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start nginx service
    service:
      name: nginx
      state: started  ; start the service
      enabled: yes    ; enabled the service